In [19]:
from sklearn import datasets

In [20]:
iris = datasets.load_iris()

In [1]:
iris.data.shape

NameError: name 'iris' is not defined

In [33]:
iris.data
#iris.data.shape

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [32]:
iris.target
#iris.target.shape

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Vector Calculations

In [136]:
import numpy as np
at= np.array([1,0,0]) #weights
bt = np.array([1,0.5,2.5,2.5,0.5,1]) #margin
yt = np.array([[1,0,2], [1,1,2], [1,2,1], [-1,3,-1], [-1,2,1], [-1,3,2]]) #features
n = 0.1

In [137]:
for i in range(0,6):
    print(np.inner(at,yt[i,:]))
    at = at+n*(bt[i]-np.inner(at,yt[i,:]))*yt[i,:]
    print(at)

1
[1. 0. 0.]
1.0
[ 0.95 -0.05 -0.1 ]
0.75
[1.125 0.3   0.075]
-0.2999999999999998
[ 0.845  1.14  -0.205]
1.23
[ 0.918  0.994 -0.278]
1.508
[ 0.9688  0.8416 -0.3796]


In [138]:
for i in range(0,6):
    print(np.inner(at,yt[i,:]))
    at = at+n*(bt[i]-np.inner(at,yt[i,:]))*yt[i,:]
    print(at)

0.2095999999999999
[ 1.04784  0.8416  -0.22152]
1.4464
[ 0.9532   0.74696 -0.4108 ]
2.0363199999999995
[ 0.999568  0.839696 -0.364432]
1.8839519999999998
[ 0.9379632  1.0245104 -0.4260368]
0.6850208000000002
[ 0.95646528  0.98750624 -0.44453888]
1.1169756800000001
[ 0.96816285  0.95241354 -0.46793402]


In [104]:
#yt[3,:]

array([-1,  3, -1])

In [107]:
#np.inner(at,yt[3,:])

-1

In [115]:
#at+n*(bt[3]-np.inner(at,yt[3,:]))*yt[3,:]

array([ 0.8,  0.6, -0.2])