In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
#iris.data # 150 samples from 4 attributes 
#iris.target # 3 classes overall 

# Calculations

### Check-calculations for exercise 6

In [39]:
import numpy as np
theta, w1, w2, lr = -1, 0, 0, 1
wt = np.array([-theta,w1,w2]) # initial weights
xt = np.array([[1,0,2], [1,1,2], [1,2,1], [1,-3,1], [1,-2,-1], [1,-3,-2]]) #features
t = np.array([1,1,1,0,0,0])
H = lambda n: 1 if n>0 else 0  # Heavyside function

In [40]:
epochs = 2
iterations = xt.shape[0]
for j in range(epochs):    
    for i in range(iterations):
        y=H(np.inner(wt,xt[i,:]))
        print(y)
        wt = wt + lr*(t[i]-y)*xt[i,:]
        print(wt)

1
[1 0 0]
1
[1 0 0]
1
[1 0 0]
1
[ 0  3 -1]
0
[ 0  3 -1]
0
[ 0  3 -1]
0
[1 3 1]
1
[1 3 1]
1
[1 3 1]
0
[1 3 1]
0
[1 3 1]
0
[1 3 1]


## Exercise for coursework

In [41]:
import numpy as np
theta, w1, w2, lr = -0.5, -7.5, 1.5, 1
wt = np.array([-theta,w1,w2]) # initial weights
xt = np.array([[1,0,2], [1,1,2], [1,2,1], [1,-3,1], [1,-2,-1], [1,-3,-2]]) #features
t = np.array([1,1,1,0,0,0])
H = lambda n: 1 if n>0 else 0.5 if n==0 else 0  # Heavyside function

In [44]:
epochs = 2
iterations = xt.shape[0]
for j in range(epochs):    
    for i in range(iterations):
        y=H(np.inner(wt,xt[i,:]))
        print(y)
        wt = wt + lr*(t[i]-y)*xt[i,:]
        print(wt)

1
[ 0.5 -7.5  1.5]
0
[ 1.5 -6.5  3.5]
0
[ 2.5 -4.5  4.5]
1
[ 1.5 -1.5  3.5]
1
[0.5 0.5 4.5]
0
[0.5 0.5 4.5]
1
[0.5 0.5 4.5]
1
[0.5 0.5 4.5]
1
[0.5 0.5 4.5]
1
[-0.5  3.5  3.5]
0
[-0.5  3.5  3.5]
0
[-0.5  3.5  3.5]
