# Loading and preparing the data

In [1]:
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()

In [2]:
#iris.data # 150 samples from 4 attributes 
#iris.target # 3 classes overall 

In [3]:
dataset = np.c_[np.ones(iris.data.shape[0]), iris.data] # dataset prepared in compact notation
#dataset

In [5]:
iris_class = (iris.target==0).astype(int) # iris class amended with output 1 for class=0 and 0 otherwise
iris_class

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Calculations

## Exercise for coursework

In [6]:
import numpy as np
theta, w1, w2, w3, w4, lr = -0.5, 3.5, -2.5, -1.5, -2.5, 0.10 
wt = np.array([-theta,w1,w2,w3,w4]) # initial weights
xt = dataset #features
t = iris_class
H = lambda n: 1 if n>0 else 0.5 if n==0 else 0  # Heavyside function

In [7]:
epochs = 2
iterations = xt.shape[0]
for j in range(epochs):    
    for i in range(iterations):
        y=H(np.inner(wt,xt[i,:]))
        wt = wt + lr*(t[i]-y)*xt[i,:]
print(wt)

[ 0.4   2.55 -2.62 -2.53 -2.82]


## Percentages calculations

In [8]:
wt_b = np.array([-theta,w1,w2,w3,w4]) # weights before training
#xt.T #transpose of dataset
wx = wt_b.dot(xt.T) # inner product array
vH = np.vectorize(H) # vectorize the Heavyside function
vH(wx) # applying the H to the inner product array to find predicted class

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [9]:
np.sum(vH(wx)==t)/t.shape[0] # Percentage similarity between predicted and actual

0.35333333333333333

In [10]:
wt # weights after training
wx_new = wt.dot(xt.T) # inner product array
vH(wx_new) # predicted class after training

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.sum(vH(wx_new)==t)/t.shape[0] # Percentage similarity between predicted and actual

0.8